### PR TITLE
Custom attributes

### PR DESCRIPTION
**Pull request by tomek-he-him**
After all, custom attributes are the most convenient way to communicate with web components. I just wanted to test it out – so why not contribute that to your pioneer example :)

### CODE REVIEW

**Comment by tomek-he-him** [comment]
By the way, this PR includes changes from #1. I know it’s not the way it _should_ be – but at least it saves us the pain of resolving merge conflicts. There would be at least one otherwise.

**Comment by tomek-he-him** [comment]
@ohanhi, is there anything I can do to help push this forward? I think it’s a valuable thing to show how `<elm-element>` communicates with the world through attributes.

**Comment by ohanhi** [comment]
@tomekwi Thanks for taking the time to improve upon the example element! For some reason, GitHub hasn't notified me about the PRs before today. That's why I haven't reacted. I'll have a look at #2 and #3 now, I already merged #1. :)

**Comment by tomek-he-him** [comment]
No problem! It’s been a pleasure to get my hands dirty with Elm :)

**Pull request merged**
